name: Release
permissions:
  contents: write # necesario para push de commits y tags
  pull-requests: write
  issues: write
  id-token: write
on:
  push:
    branches:
      - main
      - next
      - beta
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: npm run test:unit
      - run: npm run test:pack
      - run: npx playwright install --with-deps chromium
      - run: npm run test:e2e
      - run: npm run build
        env:
          NODE_ENV: "production"
      - run: npm audit signatures
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
